#!/bin/bash

# ============================================================================
# Aromatic Motif Scaffolding Pipeline
# ============================================================================
# This script runs the motif scaffolding workflow:
#   1. RFdiffusion  - Design antibody backbone with fixed motif in CDR loop
#   2. AntiBMPNN    - Design sequences (motif residues stay fixed)
#   3. RF2          - Predict/refine final structures
#
# Prerequisites:
#   - A combined PDB file with target (chain A) + motif (chain B)
#     Generated by an external aromatic optimization tool
#   - A framework antibody PDB in HLT format
#
# Usage: bash scripts/examples/motif_scaffolding_pipeline.sh
# ============================================================================

set -e  # Exit on error

# ============================================================================
# EDITABLE PARAMETERS
# ============================================================================

# Input files
FRAMEWORK_PDB="your_framework.pdb"          # Antibody framework (HLT format)
MOTIF_COMBINED_PDB="motif_1_combined.pdb"   # Combined motif+target PDB (target=chain A, motif=last chain)

# Output directory
OUTPUT_DIR="motif_scaffolding_output"

# RFdiffusion parameters
NUM_DESIGNS=100                        # Number of backbone designs
MOTIF_CDR="H3"                         # CDR loop to scaffold motif into
DESIGN_LOOPS="H1:,H2:,H3:10-16,L1:,L2:,L3:"  # H3 range must fit motif + flanks
HOTSPOTS=""                            # Target hotspot residues (optional)
DIFFUSER_T=50                          # Diffusion timesteps

# AntiBMPNN / ProteinMPNN parameters
NUM_SEQS=4                             # Sequences per backbone
SAMPLING_TEMP=0.2                      # Sampling temperature
# Weights auto-resolved: AntiBMPNN if installed (run scripts/setup_antibmpnn.sh), else vanilla ProteinMPNN

# RF2 parameters
NUM_RECYCLES=10

# ============================================================================
# SETUP
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

mkdir -p "$OUTPUT_DIR"

echo "=============================================="
echo "Aromatic Motif Scaffolding Pipeline"
echo "=============================================="
echo "Framework: $FRAMEWORK_PDB"
echo "Motif:     $MOTIF_COMBINED_PDB -> CDR $MOTIF_CDR"
echo "Output:    $OUTPUT_DIR"
echo "=============================================="

# ============================================================================
# STEP 1: RFdiffusion with motif scaffolding
# ============================================================================

echo ""
echo "[Step 1/3] Running RFdiffusion with motif scaffolding..."
echo "  - Designing $NUM_DESIGNS backbones"
echo "  - Motif scaffolded into $MOTIF_CDR"
echo "  - Loop lengths: $DESIGN_LOOPS"

RFDIFF_CMD="uv run rfdiffusion \
    --framework \"$FRAMEWORK_PDB\" \
    --output \"$OUTPUT_DIR/designs/ab_des\" \
    --num-designs $NUM_DESIGNS \
    --design-loops \"$DESIGN_LOOPS\" \
    --motif \"$MOTIF_COMBINED_PDB\" \
    --motif-cdr \"$MOTIF_CDR\" \
    --diffuser-t $DIFFUSER_T"

if [ -n "$HOTSPOTS" ]; then
    RFDIFF_CMD="$RFDIFF_CMD --hotspots \"$HOTSPOTS\""
fi

eval $RFDIFF_CMD

echo "[Step 1/3] RFdiffusion complete."

# ============================================================================
# STEP 2: ProteinMPNN with motif fixed positions
# ============================================================================

echo ""
echo "[Step 2/3] Running AntiBMPNN / ProteinMPNN..."
echo "  - Generating $NUM_SEQS sequences per backbone"
echo "  - Motif residues will remain fixed"
echo "  - Weights: AntiBMPNN if installed, else vanilla ProteinMPNN"

# Run ProteinMPNN on each design, passing the motif fixed positions file
for design_pdb in "$OUTPUT_DIR"/designs/ab_des_*.pdb; do
    base=$(basename "$design_pdb" .pdb)
    motif_json="$OUTPUT_DIR/designs/${base}_motif_fixed.json"

    MPNN_ARGS="-pdbdir $OUTPUT_DIR/designs -outpdbdir $OUTPUT_DIR/mpnn_designs \
        -loop_string H1,H2,H3,L1,L2,L3 \
        -seqs_per_struct $NUM_SEQS \
        -temperature $SAMPLING_TEMP"

    if [ -f "$motif_json" ]; then
        MPNN_ARGS="$MPNN_ARGS -motif_fixed_positions $motif_json"
    fi

    uv run python scripts/proteinmpnn_interface_design.py $MPNN_ARGS
    break  # Only process first design as example; remove this line for full run
done

echo "[Step 2/3] ProteinMPNN complete."

# ============================================================================
# STEP 3: RF2 - Predict/refine structures
# ============================================================================

echo ""
echo "[Step 3/3] Running RF2..."

uv run python scripts/rf2_predict.py \
    -pdbdir "$OUTPUT_DIR/mpnn_designs" \
    -outpdbdir "$OUTPUT_DIR/rf2_predictions"

echo "[Step 3/3] RF2 complete."

# ============================================================================
# SUMMARY
# ============================================================================

echo ""
echo "=============================================="
echo "Motif Scaffolding Pipeline Complete!"
echo "=============================================="
echo "Outputs:"
echo "  1. RFdiffusion backbones: $OUTPUT_DIR/designs/"
echo "  2. ProteinMPNN sequences: $OUTPUT_DIR/mpnn_designs/"
echo "  3. RF2 predictions:       $OUTPUT_DIR/rf2_predictions/"
echo ""
echo "The motif residues should remain at their original coordinates"
echo "in the designed CDR loop. Verify by comparing motif atom positions."
echo "=============================================="
