#!/bin/bash

# ============================================================================
# Aromatic Motif Scaffolding Pipeline
# ============================================================================
# This script runs the motif scaffolding workflow:
#   1. RFdiffusion  - Design antibody backbone with fixed motif in CDR loop
#   2. AntiBMPNN    - Design sequences (motif residues stay fixed)
#   3. Boltz2       - Predict structures + confidence metrics
#
# Conda environments:
#   - Steps 1 & 2 run in the "RFantibody" conda environment
#   - Step 3 runs in the "boltz_2.2.1" conda environment
#
# Prerequisites:
#   - A combined PDB file with target (chain A) + motif (chain B)
#     Generated by an external aromatic optimization tool
#   - A framework antibody PDB in HLT format
#   - Both conda environments set up and working
#
# Usage: bash scripts/examples/motif_scaffolding_pipeline.sh
# ============================================================================

set -e  # Exit on error

# ============================================================================
# EDITABLE PARAMETERS
# ============================================================================

# Input files
FRAMEWORK_PDB="your_framework.pdb"          # Antibody framework (HLT format)
MOTIF_COMBINED_PDB="motif_1_combined.pdb"   # Combined motif+target PDB (target=chain A, motif=last chain)

# Output directory
OUTPUT_DIR="motif_scaffolding_output"

# Conda environments
RFANTIBODY_ENV="RFantibody"            # Environment for RFdiffusion + AntiBMPNN
BOLTZ2_ENV="boltz_2.2.1"              # Environment for Boltz2 prediction

# RFdiffusion parameters
NUM_DESIGNS=100                        # Number of backbone designs
MOTIF_CDR="H3"                         # CDR loop to scaffold motif into
DESIGN_LOOPS="H1:,H2:,H3:10-16,L1:,L2:,L3:"  # H3 range must fit motif + flanks
HOTSPOTS=""                            # Target hotspot residues (optional)
DIFFUSER_T=50                          # Diffusion timesteps

# AntiBMPNN / ProteinMPNN parameters
NUM_SEQS=4                             # Sequences per backbone
SAMPLING_TEMP=0.2                      # Sampling temperature
# Weights auto-resolved: AntiBMPNN if installed (run scripts/setup_antibmpnn.sh), else vanilla ProteinMPNN

# Boltz2 parameters
DIFFUSION_SAMPLES=1                    # Diffusion samples per design (increase for re-ranking)
MSA_SERVER_URL="http://a3m-2023.mmseqs.com"
BOLTZ_CACHE=""                         # Boltz2 cache dir (empty = default)

# ============================================================================
# SETUP
# ============================================================================

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "$SCRIPT_DIR/../.." && pwd)"
cd "$PROJECT_ROOT"

mkdir -p "$OUTPUT_DIR"

# Initialize conda
if command -v conda &>/dev/null; then
    CONDA_BASE=$(conda info --base 2>/dev/null)
    source "$CONDA_BASE/etc/profile.d/conda.sh"
else
    echo "Error: conda not found. Both environments require conda."
    exit 1
fi

echo "=============================================="
echo "Aromatic Motif Scaffolding Pipeline"
echo "=============================================="
echo "Framework: $FRAMEWORK_PDB"
echo "Motif:     $MOTIF_COMBINED_PDB -> CDR $MOTIF_CDR"
echo "Output:    $OUTPUT_DIR"
echo "Envs:      $RFANTIBODY_ENV (Steps 1-2) | $BOLTZ2_ENV (Step 3)"
echo "=============================================="

# ============================================================================
# STEP 1: RFdiffusion with motif scaffolding (RFantibody env)
# ============================================================================

echo ""
echo "[Step 1/3] Running RFdiffusion with motif scaffolding..."
echo "  - Designing $NUM_DESIGNS backbones"
echo "  - Motif scaffolded into $MOTIF_CDR"
echo "  - Loop lengths: $DESIGN_LOOPS"

conda activate "$RFANTIBODY_ENV"

RFDIFF_CMD="uv run rfdiffusion \
    --framework \"$FRAMEWORK_PDB\" \
    --output \"$OUTPUT_DIR/designs/ab_des\" \
    --num-designs $NUM_DESIGNS \
    --design-loops \"$DESIGN_LOOPS\" \
    --motif \"$MOTIF_COMBINED_PDB\" \
    --motif-cdr \"$MOTIF_CDR\" \
    --diffuser-t $DIFFUSER_T"

if [ -n "$HOTSPOTS" ]; then
    RFDIFF_CMD="$RFDIFF_CMD --hotspots \"$HOTSPOTS\""
fi

eval $RFDIFF_CMD

echo "[Step 1/3] RFdiffusion complete."

# ============================================================================
# STEP 2: AntiBMPNN with motif fixed positions (RFantibody env)
# ============================================================================

echo ""
echo "[Step 2/3] Running AntiBMPNN / ProteinMPNN..."
echo "  - Generating $NUM_SEQS sequences per backbone"
echo "  - Motif residues will remain fixed"
echo "  - Weights: AntiBMPNN if installed, else vanilla ProteinMPNN"

# Run ProteinMPNN on each design, passing the motif fixed positions file
for design_pdb in "$OUTPUT_DIR"/designs/ab_des_*.pdb; do
    base=$(basename "$design_pdb" .pdb)
    motif_json="$OUTPUT_DIR/designs/${base}_motif_fixed.json"

    MPNN_ARGS="-pdbdir $OUTPUT_DIR/designs -outpdbdir $OUTPUT_DIR/mpnn_designs \
        -loop_string H1,H2,H3,L1,L2,L3 \
        -seqs_per_struct $NUM_SEQS \
        -temperature $SAMPLING_TEMP"

    if [ -f "$motif_json" ]; then
        MPNN_ARGS="$MPNN_ARGS -motif_fixed_positions $motif_json"
    fi

    uv run python scripts/proteinmpnn_interface_design.py $MPNN_ARGS
    break  # Only process first design as example; remove this line for full run
done

echo "[Step 2/3] ProteinMPNN complete."

conda deactivate

# ============================================================================
# STEP 3: Boltz2 — Structure prediction + confidence (boltz_2.2.1 env)
# ============================================================================

echo ""
echo "[Step 3/3] Running Boltz2 structure prediction..."
echo "  - Converting PDBs to Boltz2 YAML format"
echo "  - Predicting with $DIFFUSION_SAMPLES diffusion sample(s)"

# 3a. Prepare Boltz2 YAML inputs (can run in RFantibody env — only needs pyyaml)
conda activate "$RFANTIBODY_ENV"

python scripts/prepare_boltz2_input.py \
    -i "$OUTPUT_DIR/mpnn_designs" \
    -o "$OUTPUT_DIR/boltz2_input"

conda deactivate

# 3b. Run Boltz2 prediction (boltz_2.2.1 env)
conda activate "$BOLTZ2_ENV"

BOLTZ_CMD="boltz predict \"$OUTPUT_DIR/boltz2_input\" \
    --out_dir \"$OUTPUT_DIR/boltz2_output\" \
    --diffusion_samples $DIFFUSION_SAMPLES \
    --use_msa_server \
    --msa_server_url=$MSA_SERVER_URL \
    --use_potentials \
    --write_full_pae \
    --write_full_pde"

if [ -n "$BOLTZ_CACHE" ]; then
    BOLTZ_CMD="$BOLTZ_CMD --cache \"$BOLTZ_CACHE\""
fi

echo "Running: $BOLTZ_CMD"
eval $BOLTZ_CMD

conda deactivate

# 3c. Extract metrics (RFantibody env — needs numpy + pandas)
conda activate "$RFANTIBODY_ENV"

python scripts/extract_boltz2_metrics.py \
    -i "$OUTPUT_DIR/boltz2_output" \
    -d "$OUTPUT_DIR/mpnn_designs" \
    -o "$OUTPUT_DIR/boltz2_metrics.csv" \
    --rank-by ipTM

conda deactivate

echo "[Step 3/3] Boltz2 complete."

# ============================================================================
# SUMMARY
# ============================================================================

echo ""
echo "=============================================="
echo "Motif Scaffolding Pipeline Complete!"
echo "=============================================="
echo "Outputs:"
echo "  1. RFdiffusion backbones: $OUTPUT_DIR/designs/"
echo "  2. AntiBMPNN sequences:   $OUTPUT_DIR/mpnn_designs/"
echo "  3. Boltz2 structures:     $OUTPUT_DIR/boltz2_output/"
echo "  4. Ranked metrics:        $OUTPUT_DIR/boltz2_metrics.csv"
echo ""
echo "The motif residues should remain at their original coordinates"
echo "in the designed CDR loop. Verify by comparing motif atom positions."
echo ""
echo "Review the metrics CSV to identify top candidates by ipTM score."
echo "=============================================="
