#!/usr/bin/env bash
# =============================================================================
# Run Boltz2 structure prediction in its dedicated conda environment.
#
# This script activates the Boltz2 conda environment and runs `boltz predict`
# on YAML input files generated by prepare_boltz2_input.py.
#
# Usage:
#   bash scripts/run_boltz2_predict.sh \
#       -i boltz2_input/ \
#       -o boltz2_output/ \
#       [--samples 5] \
#       [--env boltz_2.2.1] \
#       [--cache /path/to/.boltz]
#
# The script handles conda environment activation automatically.
# =============================================================================

set -euo pipefail

# ---- Defaults ---------------------------------------------------------------

BOLTZ_CONDA_ENV="boltz_2.2.1"
DIFFUSION_SAMPLES=1
MSA_SERVER_URL="http://a3m-2023.mmseqs.com"
BOLTZ_CACHE=""          # Empty = let boltz use its default
INPUT_DIR=""
OUTPUT_DIR=""
EXTRA_ARGS=""

# ---- Parse arguments --------------------------------------------------------

print_usage() {
    cat <<EOF
Usage: $(basename "$0") -i INPUT_DIR -o OUTPUT_DIR [OPTIONS]

Required:
  -i, --input       Directory containing Boltz2 YAML files
  -o, --output      Output directory for predictions

Options:
  --samples N       Number of diffusion samples per input (default: $DIFFUSION_SAMPLES)
  --env NAME        Conda environment name (default: $BOLTZ_CONDA_ENV)
  --cache PATH      Boltz2 cache directory (default: auto)
  --msa-url URL     MSA server URL (default: $MSA_SERVER_URL)
  --extra "ARGS"    Additional arguments passed directly to boltz predict
  -h, --help        Show this help message
EOF
}

while [[ $# -gt 0 ]]; do
    case "$1" in
        -i|--input)     INPUT_DIR="$2"; shift 2 ;;
        -o|--output)    OUTPUT_DIR="$2"; shift 2 ;;
        --samples)      DIFFUSION_SAMPLES="$2"; shift 2 ;;
        --env)          BOLTZ_CONDA_ENV="$2"; shift 2 ;;
        --cache)        BOLTZ_CACHE="$2"; shift 2 ;;
        --msa-url)      MSA_SERVER_URL="$2"; shift 2 ;;
        --extra)        EXTRA_ARGS="$2"; shift 2 ;;
        -h|--help)      print_usage; exit 0 ;;
        *)              echo "Unknown option: $1"; print_usage; exit 1 ;;
    esac
done

if [ -z "$INPUT_DIR" ] || [ -z "$OUTPUT_DIR" ]; then
    echo "Error: --input and --output are required."
    print_usage
    exit 1
fi

# ---- Validate input ---------------------------------------------------------

YAML_COUNT=$(find "$INPUT_DIR" -name "*.yaml" -type f 2>/dev/null | wc -l)
if [ "$YAML_COUNT" -eq 0 ]; then
    echo "Error: No YAML files found in $INPUT_DIR"
    exit 1
fi

mkdir -p "$OUTPUT_DIR"

echo "============================================"
echo " Boltz2 Structure Prediction"
echo "============================================"
echo "  Environment:  $BOLTZ_CONDA_ENV"
echo "  Input:        $INPUT_DIR ($YAML_COUNT YAML files)"
echo "  Output:       $OUTPUT_DIR"
echo "  Samples:      $DIFFUSION_SAMPLES"
echo "  MSA server:   $MSA_SERVER_URL"
echo "============================================"
echo ""

# ---- Activate conda environment ---------------------------------------------

# Support both conda and mamba
if command -v conda &>/dev/null; then
    CONDA_BASE=$(conda info --base 2>/dev/null)
    source "$CONDA_BASE/etc/profile.d/conda.sh"
elif command -v mamba &>/dev/null; then
    CONDA_BASE=$(mamba info --base 2>/dev/null)
    source "$CONDA_BASE/etc/profile.d/conda.sh"
else
    echo "Error: Neither conda nor mamba found. Cannot activate $BOLTZ_CONDA_ENV."
    exit 1
fi

conda activate "$BOLTZ_CONDA_ENV"
echo "Activated environment: $BOLTZ_CONDA_ENV"
echo "  Python: $(which python)"
echo "  Boltz:  $(which boltz 2>/dev/null || echo 'NOT FOUND')"
echo ""

# ---- Build boltz predict command --------------------------------------------

CMD="boltz predict \"$INPUT_DIR\""
CMD="$CMD --out_dir \"$OUTPUT_DIR\""
CMD="$CMD --diffusion_samples $DIFFUSION_SAMPLES"
CMD="$CMD --use_msa_server"
CMD="$CMD --msa_server_url=$MSA_SERVER_URL"
CMD="$CMD --use_potentials"
CMD="$CMD --write_full_pae"
CMD="$CMD --write_full_pde"

if [ -n "$BOLTZ_CACHE" ]; then
    CMD="$CMD --cache \"$BOLTZ_CACHE\""
fi

if [ -n "$EXTRA_ARGS" ]; then
    CMD="$CMD $EXTRA_ARGS"
fi

echo "Running: $CMD"
echo ""

# ---- Execute ----------------------------------------------------------------

START_TIME=$(date +%s)

eval $CMD
RC=$?

END_TIME=$(date +%s)
ELAPSED=$((END_TIME - START_TIME))

echo ""
echo "============================================"
if [ $RC -eq 0 ]; then
    echo " Boltz2 prediction complete (${ELAPSED}s)"
else
    echo " Boltz2 prediction FAILED (exit code $RC, ${ELAPSED}s)"
fi
echo "============================================"

# ---- Deactivate conda -------------------------------------------------------
conda deactivate

exit $RC
